name: multi platform test

on:
  push:
    branches: [ "trunk", "develop" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: windows-latest
            cpp_compiler: cl
          - os: ubuntu-latest
            cpp_compiler: g++
          - os: macos-latest
            cpp_compiler: clang++

    steps:
    - uses: actions/checkout@v3

    - name: Set reusable strings
      id: strings
      shell: bash
      run: echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Install dependencies Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: >
        sudo apt-get update && sudo apt-get install libboost-dev mrc

    - name: Install Boost Windows
      if: matrix.os == 'windows-latest'
      uses: MarkusJx/install-boost@v2.4.4
      id: install-boost
      with:
          boost_version: 1.82.0
          platform_version: 2019
          toolset: msvc

    - name: Install ZLib Window
      if: matrix.os == 'windows-latest'
      run: ./tools/depends.cmd
      shell: cmd

    - name: Install Boost macOS
      if: matrix.os == 'macos-latest'
      run: >
        brew install boost

    - name: Configure CMake
      env:
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_BUILD_TYPE=Release
        -S ${{ github.workspace }}
        
    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release
      
    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config Release --output-on-failure

    - name: Install
      if: matrix.os != 'windows-latest'
      run: sudo cmake --install ${{ steps.strings.outputs.build-output-dir }} --config Release
